services:
  cpp_dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        IMAGE_NAME: "cpp-dev-environment"
    container_name: cpp_dev_container
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - type: bind
        source: ..
        target: /app
        bind:
          create_host_path: true
    working_dir: /app
    stdin_open: true    # Permite mantener el stdin abierto para una sesión interactiva
    tty: true           # Asigna una tty para que el contenedor soporte interactividad

  python_automation:
    image: python:3.13-slim
    container_name: python_automation_container
    volumes:
      - type: bind
        source: ..
        target: /app
        bind:
          create_host_path: true
    working_dir: /app
    command:
      - tail
      - -f
      - /dev/null